from collections.abc import Sequence
import numpy as np
from numpy.typing import NDArray

class SentenceTransformer:
    def __init__(self, model_name_or_path: str) -> None: ...
    def encode(self, sentences: Sequence[str], *, normalize_embeddings: bool = ...) -> NDArray[np.float32]: ...

class CrossEncoder:
    def __init__(self, model_name_or_path: str) -> None: ...
    def predict(self, sentences: Sequence[tuple[str, str]]) -> NDArray[np.float32]: ...
